spring:
  application:
    name: lunchrecommender

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587   # SMTP 서버 포트 (예: TLS의 경우 일반적으로 587, SSL의 경우 465)
    properties:
      mail:
        smtp:
          auth: true      # SMTP 인증 사용 여부
          starttls:
            enable: true  # STARTTLS 사용 여부 (TLS 암호화)

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: your-client-id  # 네이버 클라이언트 ID
            client-secret: your-client-secret  # 네이버 클라이언트 시크릿
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope: profile
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  port: 443
  ssl:
    enabled: true
    key-store: src/main/resources/bootsecurity.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: bootsecurity
